export type MoistureStage = 'green' | 'fiber_saturation' | 'bound_water' | 'target';
export type LotState = 'queued' | 'conditioning' | 'drying' | 'equalizing' | 'completed' | 'aborted';
export type ScheduleLifecycle = 'draft' | 'calculating' | 'proposed' | 'failed' | 'reviewed' | 'accepted' | 'voided';
export type AdaptivePlanMode = 'adaptive' | 'equalizing_hold';
export type CheckpointAction = 'adaptive_follow' | 'equalizing_recheck';
export interface DryingKiln { id:string; kiln_code:string; name:string; capacity_m3:number; max_temperature_c:number; min_humidity_pct:number; airflow_class:string; owner_team:string; kiln_state:string; commissioned_at:string; updated_at:string; lots?:TimberLot[] }
export interface TimberLot { id:string; lot_code:string; kiln_id:string; species:string; thickness_mm:number; volume_m3:number; initial_moisture_pct:number; target_moisture_pct:number; quality_grade:string; loaded_at:string; lot_state:LotState; created_by:string; version:number; kiln?:DryingKiln }
export interface MoistureReading { id:string; timber_lot_id:string; sample_position:string; measured_at:string; moisture_pct:number; dry_bulb_c:number; wet_bulb_c:number; source_checksum:string; reading_quality:string; quality_note:string; imported_by:string }
export interface AdaptiveCheckpoint { sequence:number; action:CheckpointAction; review_at:string; interval_hours:number; target_dry_bulb_c:number; target_humidity_pct:number; predicted_moisture_pct:number; interim_reminder:boolean; interim_reminder_at?:string; note:string }
export interface AdaptiveEnvelopeLimit { parameter:string; material_limit:number; kiln_limit:number; effective_limit:number; constrained_by:string }
export interface AdaptivePlan { mode:AdaptivePlanMode; stage:string; rule_id:string; rule_version:string; profile_id:string; generated_at:string; window_until:string; current_dry_bulb_c:number; current_humidity_pct:number; current_moisture_pct:number; target_moisture_pct:number; cadence_hours:number; paired_event_count:number; checkpoints:AdaptiveCheckpoint[]; warnings:string[]; effective_envelope:AdaptiveEnvelopeLimit[]; hold_reasons?:string[]; basis:string }
export interface FrozenBaselineView { baseline_schedule_id:string; baseline_finish_at:string|null; current_finish_at:string|null; finish_delta_hours:number; baseline_risk_score:number; current_risk_score:number; risk_delta:number }
export interface DryingSchedule { id:string; timber_lot_id:string; kiln_snapshot:string; algorithm_version:string; input_hash:string; stages_json:string; recommended_changes_json:string; rule_evidence_json:string; adaptive_plan_json:string; predicted_finish_at:string|null; defect_risk_score:number; schedule_state:ScheduleLifecycle; explanation:string; failure_reason:string; frozen_at?:string|null; frozen_by?:string; reviewed_by?:string; calculated_at:string; created_by:string; version:number; frozen_baseline_view?:FrozenBaselineView|null }
