export type MoistureStage = 'green' | 'fiber_saturation' | 'bound_water' | 'target';
export type LotState = 'queued' | 'conditioning' | 'drying' | 'equalizing' | 'completed' | 'aborted';
export type ScheduleLifecycle = 'draft' | 'calculating' | 'proposed' | 'failed' | 'reviewed' | 'accepted' | 'voided';
export type PlanMode = 'adaptive' | 'equalizing_retest';
export interface DryingKiln { id:string; kiln_code:string; name:string; capacity_m3:number; max_temperature_c:number; min_humidity_pct:number; airflow_class:string; owner_team:string; kiln_state:string; commissioned_at:string; updated_at:string; lots?:TimberLot[] }
export interface TimberLot { id:string; lot_code:string; kiln_id:string; species:string; thickness_mm:number; volume_m3:number; initial_moisture_pct:number; target_moisture_pct:number; quality_grade:string; loaded_at:string; lot_state:LotState; created_by:string; version:number; kiln?:DryingKiln }
export interface MoistureReading { id:string; timber_lot_id:string; sample_position:string; measured_at:string; moisture_pct:number; dry_bulb_c:number; wet_bulb_c:number; source_checksum:string; reading_quality:string; quality_note:string; imported_by:string }
export interface PlanEnvelope { max_temperature:number; min_humidity:number; max_gradient:number; max_drying_rate:number; temp_constrained_by:string; humidity_constrained_by:string }
export interface Checkpoint { index:number; review_at:string; interval_hours:number; target_dry_bulb_c:number; target_humidity_pct:number; expected_moisture_pct:number; supplemental_test:boolean; note:string }
export interface StageMetric { stage:string; average_moisture:number; gradient:number; drying_rate:number; anomalies:number }
export interface RuleEvidence { rule_id:string; version:string; constraint:string; observed:number; limit:number; passed:boolean; source:string }
export interface Suggestion { parameter:string; current:number; suggested:number; rule:string; risk_delta:number }
export interface FrozenPlanComparison { baseline_schedule_id:string; frozen_at:string|null; predicted_finish_at:string|null; baseline_finish_at:string|null; finish_delta_hours:number; risk:number; baseline_risk:number; risk_delta:number }
export interface DryingSchedule { id:string; timber_lot_id:string; kiln_snapshot:string; algorithm_version:string; input_hash:string; stages_json:string; recommended_changes_json:string; rule_evidence_json:string; checkpoints_json:string; plan_mode:PlanMode|''; predicted_finish_at:string|null; defect_risk_score:number; schedule_state:ScheduleLifecycle; explanation:string; failure_reason:string; frozen_at:string|null; frozen_by:string; frozen_snapshot:string; baseline_schedule_id:string; comparison_json:string; frozen_comparison?:FrozenPlanComparison|null; calculated_at:string; created_by:string; reviewed_by:string; version:number }
